apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-explorer-miles-systems-tls
  namespace: server-explorer
spec:
  secretName: server-explorer-miles-systems-tls
  dnsNames:
    - explorer.miles.systems
    - server-explorer.miles.systems
  issuerRef:
    name: letsencrypt-miles-systems-dns-prod
    kind: ClusterIssuer
